language: node_js
node_js: 12

script:
  - yarn
  - yarn test
  - yarn build

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH
    skip_cleanup: true
    tag: next
    on:
      tags: true
      branch: next

cache:
  yarn: true
